name: Builds

run-name: Builds - ${{ github.event.head_commit.message }}

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
  # GitHub Actions scheduled workflows (the on: schedule trigger) 
  #   must exist on the default branch (usually main or master) of your repository to be triggered.
  schedule:
    # schedule
    # '0 12 * * *'
    # This is UTZ 12 noon
    # https://github.com/BtbN/FFmpeg-Builds/blob/master/.github/workflows/build.yml
    # + 2 hours to build
    # https://github.com/BtbN/FFmpeg-Builds/releases
    #
    # My schedule is three(3) hours after the FFmpeg build starts
    # UTC 15 
#   - cron: '0 15 * * *'  # Runs daily at 3 p.m. UTZ time
    - cron: '30 * * * *'  # Runs every hour at the 1/2 point in time
    # github.event_name == 'schedule'

permissions:
  contents: write

jobs:
  build:
    name: Build matid ${{ matrix.matid }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - matid: 01
          os: windows-2025
          GithubActionsIgnoreFail: false

        - matid: 02
          os: windows-2025
          GithubActionsIgnoreFail: true
          RunOnTimer: true

    steps:

    - name: Skip This Matrix Item matid ${{ matrix.matid }}
      shell: bash
      run: |
        set -x -v -e
        export  SKIP="${{ github.event_name == 'schedule' && matrix.RunOnTimer != 'true' && 'true' || 'false' }}"
        if [ "${SKIP}" == "" ]; then export SKIP="notset" ; fi
        echo "SKIP=${SKIP}" >> ${GITHUB_ENV}

        echo "SKIP: ${SKIP}"


    - name: General Shell Environment Variables made using Bash
      if: >- 
        ${{ env.SKIP != 'true' 
        }}
      shell: bash                     # redundant, because it is my defined matrix default
      run: |
        set -x -v -e

        export TODAYSDATETIME=$(date +"%Y-%m-%d-%H-%M")
        if [ "${TODAYSDATETIME}" == "" ]; then export TODAYSDATETIME="notset" ; fi
        echo  "TODAYSDATETIME=${TODAYSDATETIME}" >> ${GITHUB_ENV}

        echo  "TODAYSDATETIME: ${TODAYSDATETIME}"

        export  HEAD7_GITHUB_SHA="$(echo "${GITHUB_SHA}" | cut -c -7)"
        if [ "${HEAD7_GITHUB_SHA}" == "" ]; then export HEAD7_GITHUB_SHA="notset" ; fi
        echo   "HEAD7_GITHUB_SHA=${HEAD7_GITHUB_SHA}" >> ${GITHUB_ENV}

        echo   "HEAD7_GITHUB_SHA: ${HEAD7_GITHUB_SHA}"

    - name: Make Artifacts and Place Them
      if: >- 
        ${{ env.SKIP != 'true' 
        }}
      shell: bash
      run: |
        mkdir Export
        echo "${{ env.TODAYSDATETIME }}-matid-${{ matrix.matid }}" > Export/test.txt


    - name: For Export Upload Artifact of ${{ env.TODAYSDATETIME }}-matid-${{ matrix.matid }}-${{ env.TODAYSDATETIME }}
      if: >- 
        ${{ env.SKIP != 'true' 
        }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.matid }}-${{ github.sha }}-${{ env.TODAYSDATETIME }}
        # if-no-files-found: warn
        path: |
          Export/


    - name: Prepare for Release Action create a new ${{ matrix.matid }}-${{ github.sha }}-${{ env.TODAYSDATETIME }}
      if: >- 
        ${{ env.SKIP != 'true' 
        }}
      shell: bash
      run: |
        7z a ${{ matrix.matid }}-${{ github.sha }}-${{ env.TODAYSDATETIME }}.zip ./Export/*

    # Note, ncipollo/release-action requires a tag
    - name: For Distribution Release Artifacts of ${{ matrix.matid }}-${{ github.sha }}-${{ env.TODAYSDATETIME }}
        # ${{ env.SKIP != 'true' && ( 
        # ( github.event_name == 'schedule' || github.ref_type == 'tag' ) 
        # ) }}
      if: >- 
        ${{ env.SKIP != 'true' }}
      uses: ncipollo/release-action@v1
      with:
        # in certain situations, the action will create a tag
        # tag: ${{ env.TODAYSDATETIME }}
        tag: ${{ github.sha }}-${{ github.event_name }}-${{ github.ref_type }}-${{ github.ref_name }}-${{ env.TODAYSDATETIME }}
        commit: ${{ github.sha }}
        allowUpdates: false
        replacesArtifacts: false
        artifacts: |
          matid-${{ matrix.matid }}-${{ github.sha }}-${{ env.TODAYSDATETIME }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
