name: Test Artifact for Release Name
run-name: Test Artifact for Release Run - ${{ github.event.head_commit.message }}

permissions:
  contents: write

on:
   push:
   pull_request:
   workflow_dispatch:

jobs:
  test_release_assets:
    runs-on: windows-2025-vs2026
    steps:
      - name: Windows Machine Stats system information
        shell: cmd
        run: |
          systeminfo > systeminfo.txt
      - name: Test Artifact for Release Step
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: |
            systeminfo.txt
          token: ${{ secrets.GITHUB_TOKEN }}
